### ISSUE TITLE
Import Error with url_quote from werkzeug.urls

### ISSUE THREAD

**Issue by brejoc** [elisa-tech/BASIL#5]
Not sure if there is something missing or if there are version mismatches. But there seems to be no `url_quote` Werkzeug version `3.0.1`. At least not in `werkzeug.urls`.

```
pdm run python3 api/api.py
Traceback (most recent call last):
  File "/Users/brejoc/repos/github/BASIL/api/api.py", line 3, in <module>
    from flask import Flask, request, send_file
  File "/Users/brejoc/repos/github/BASIL/.venv/lib/python3.11/site-packages/flask/__init__.py", line 5, in <module>
    from .app import Flask as Flask
  File "/Users/brejoc/repos/github/BASIL/.venv/lib/python3.11/site-packages/flask/app.py", line 30, in <module>
    from werkzeug.urls import url_quote
ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/Users/brejoc/repos/github/BASIL/.venv/lib/python3.11/site-packages/werkzeug/urls.py)
```

**Comment by pellecchialuigi** [comment]
In accord with what described at https://stackoverflow.com/questions/77213053/importerror-cannot-import-name-url-quote-from-werkzeug-urls the error can be fixed specifying the desired version of Werkzeug==2.2.2 in the pyproject.toml file. I'll push a fix soon. Thanks a lot for filing this issue!
